### ISSUE TITLE
Section 3. Each voter is limited to one (1) vote per match per round. A voter may not vote on behalf of another person.

### ISSUE THREAD

**Issue by WinHGGG** [Hecate2/ISML_auto_voter#20]
Section 3. Each voter is limited to one (1) vote per match per round. A voter may not vote on behalf of another person.

**Comment by Hecate2** [comment]
> Section 3. Each voter is limited to one (1) vote per match per round. A voter may not vote on behalf of another person.

Had the constitution of ISML taken effect, I would neither write these programs nor release them. 
Almost ALL saimoe events go corrupted very quickly.

**Comment by Hecate2** [comment]
> Section 3. Each voter is limited to one (1) vote per match per round. A voter may not vote on behalf of another person.

You would be astonished if you see hundreds of human laborers manipulating thousands of browsers voting for characters.
